//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idz.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public System.Guid Payment_ID { get; set; }
        public System.DateTime Date { get; set; }
        public long Amount { get; set; }
        public System.Guid Client_ID { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
